ci: do not attempt releasing when local changes detected

diff --git a/scripts/release b/scripts/release
--- a/scripts/release
+++ b/scripts/release
@@ -2,4 +2,12 @@
 
 set -e
 
-release-it
+local_changes=$(git status --short)
+
+if [ "$local_changes" = "" ]; then
+	release-it --ci
+else
+	echo "Cannot release because of local changes:"
+	echo "$local_changes"
+	exit 1
+fi
